linters:
  enable:
    - gofmt
    - goimports
    - govet
    - gosimple
    - staticcheck
    - ineffassign
    - unused
    - misspell

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/dfanso/reddit-clone

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
  
run:
  timeout: 5m
  tests: true 