name: Go Format Check

on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches: [ "main", "dev" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
        golangci-lint --version

    - name: Check formatting
      run: |
        # Check if gofmt would make any changes
        result=$(gofmt -l .)
        if [ -n "$result" ]; then
          echo "The following files are not formatted correctly:"
          echo "$result"
          exit 1
        fi

    - name: Run golangci-lint
      run: golangci-lint run ./... 